### ISSUE TITLE
[BUG]Shop error

### ISSUE THREAD

**Issue by ADMTec** [pulseP1986/free-mu-cms#12]
When you click on the menu to go to the Shop, you get an error

1. Go to Main Page
2. Click on Shop on the menu
3. See error

![Captura de Tela (101)2](https://github.com/pulseP1986/free-mu-cms/assets/16466549/fcbb7d45-94ea-422a-a5f9-fbc0b9caf4fd)

```
================================================================================
02-28-2024 14:16:25.505500 #### SELECT id, item_id, item_cat, name, original_item_cat, stick_level, price FROM DmN_Shopp WHERE price >= 1 AND item_cat IN ('0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15') ORDER BY  item_cat ASC, item_id ASC
================================================================================
02-28-2024 14:16:25.506400 #### PDOException: SQLSTATE[22018]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Conversion failed when converting the varchar value '0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15' to data type int. in C:\xampp\htdocs\application\libraries\lib.db.php:105
Stack trace:
#0 C:\xampp\htdocs\application\libraries\lib.db.php(105): PDO->query('SELECT id, item...')
#1 C:\xampp\htdocs\application\models\model.shop.php(35): db->query('SELECT id, item...')
#2 C:\xampp\htdocs\application\controllers\controller.shop.php(76): Mshop->load_items('DEFAULT', 1, '16', '4')
#3 C:\xampp\htdocs\system\router.class.php(91): shop->index()
#4 C:\xampp\htdocs\system\dmn.php(26): router->route(Object(request))
#5 C:\xampp\htdocs\system\dmn.php(29): initDmN()
#6 C:\xampp\htdocs\index.php(33): require_once('C:\\xampp\\htdocs...')
#7 {main}

```

**Comment by pulseP1986** [comment]
https://github.com/pulseP1986/free-mu-cms/commit/018dd453fa6bce7585454a139bafdaaa75accb34

**Comment by ADMTec** [comment]
now it is giving another type of error

![Captura de Tela (109)](https://github.com/pulseP1986/free-mu-cms/assets/16466549/15175ec5-8900-4d41-8268-0c28eaf280c6)
