### ISSUE TITLE
[BUG]Account Manager Error

### ISSUE THREAD

**Issue by ADMTec** [pulseP1986/free-mu-cms#13]
The error appears as soon as you enter the Account Manager tab

1. Go to AdminCP
2. Click on Axxount Manager
3. See error

![Captura de Tela (102)](https://github.com/pulseP1986/free-mu-cms/assets/16466549/2b848aad-1435-4ddd-9c20-706d7d49b33c)

```
02-28-2024 16:54:59.032200 #### SELECT TOP 10 m.memb_guid, m.memb___id, m.appl_days, m.dmn_country, m.activated,  d.viptime FROM MEMB_INFO AS m LEFT JOIN [dmncms].dbo.DmN_Vip_Users AS d ON(m.memb___id Collate Database_Default = d.memb___id Collate Database_Default) WHERE memb_guid NOT IN (SELECT Top '0' memb_guid FROM MEMB_INFO  ORDER BY m.appl_days DESC)  ORDER BY m.appl_days DESC
================================================================================
02-28-2024 16:54:59.033100 #### PDOException: SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near '0'. in C:\xampp\htdocs\application\libraries\lib.db.php:105
Stack trace:
#0 C:\xampp\htdocs\application\libraries\lib.db.php(105): PDO->query('SELECT TOP 10 m...')
#1 C:\xampp\htdocs\application\models\model.admin.php(2503): db->query('SELECT TOP 10 m...')
#2 C:\xampp\htdocs\application\controllers\controller.admincp.php(5500): Madmin->load_account_list('0', '10', 'DEFAULT', '1', 'desc')
#3 C:\xampp\htdocs\system\router.class.php(91): admincp->load_accounts()
#4 C:\xampp\htdocs\system\dmn.php(26): router->route(Object(request))
#5 C:\xampp\htdocs\system\dmn.php(29): initDmN()
#6 C:\xampp\htdocs\index.php(33): require_once('C:\\xampp\\htdocs...')
#7 {main}
================================================================================
```

**Comment by pulseP1986** [comment]
Semms your version is outdated try with https://github.com/pulseP1986/free-mu-cms/releases/tag/v1.2.4.9
